1Hive/celeste-dashboard

src/abi/ERC20.json, src/abi/disputables/DisputableConvictionVoting.json, src/disputables/index.js, src/disputables/known-appIds.js, src/disputables/known-arbitrables.js, src/disputables/mappings.js, src/disputables/scriptExtractors.js
=> Disputables: Integrate conviction voting app proposal description

src/components/ClockModule.js, src/components/Dashboard/BalanceModule.js, src/components/Dashboard/panels/ActivateHNY.js, src/endpoints.js, src/hooks/useBrightIdVerification.js, src/hooks/useCourtContracts.js, src/lib/web3-utils.js, src/utils/brightId-utils.js
=> Brightid 1hive integration

package.json, src/components/Account/AccountButton.js, src/components/Account/AccountModule.js, src/components/Dashboard/Profile.js, src/components/IdentityBadge.js, src/hooks/useProfileName.js, src/lib/profile.js
=> Integrate 3box profile names

src/components/Disputes/DisputeTimeline.js, src/hooks/useDisputeTimeline.js, src/utils/dispute-utils.js
=> Dispute timeline: Prevent accordion from auto-collapsing

src/components/EmailNotifications/EmailNotificationsManager.js, src/components/RequestPanel/RequestStatus.js, yarn.lock
=> fix use wallet wrong property

src/components/Dashboard/CourtStats.js
=> Fix stretched icon

src/components/EmailNotifications/EmailNotificationsManager.js
=> Notifications modal margin

src/components/RequestPanel/RequestPanel.js
=> Show close button when requests processing failed

src/components/RequestPanel/Steps/RequestSteps.js, src/components/RequestPanel/TransactionProgress.js
=> Request panel step: Use accent color

docs/CONFIGURATION.md, src/components/Accordion/Accordion.js, src/components/Accordion/OpenedSurfaceBorder.js, src/components/Accordion/ToggleButton.js, src/components/Disputes/DisputeEvidences.js, src/components/Disputes/DisputeTimeline.js, src/theme-court.js
closes #59 
Forks Accordion component to meet style needs.
Once approved here, will do a PR to 1hive/ui repo
=> Implement new Accordion for Timeline and Comments

src/components/Dashboard/panels/ActivateHNY.js, src/components/Dashboard/panels/HNYForm.js, src/radspec.js
=> Max active amount info

src/components/Dashboard/Balance.js, src/components/Dashboard/Welcome.js, src/components/Disputes/DisputeActions.js, src/components/Disputes/DisputeOutcomeText.js, src/components/Disputes/actions/DisputeVoting.js, src/components/MainView.js, src/utils/crvoting-utils.js
- Fixes footer padding issue.
- Fixes suggested copies at #72 
- Fixes welcome banner width on mobile
- Updates Refuse to vote  => Abstain from voting
=> Suggestions

src/abi/CourtSubscriptions.json, src/actions/allowedTermsBehind.js, src/components/Dashboard/RewardsModule.js, src/hooks/useCourtContracts.js, src/hooks/useJurorSubscriptionFees.js, src/queries/court.js, src/utils/subscription-utils.js
Updates logic to follow update contract logic. More context see https://github.com/1Hive/celeste-contracts/pull/4
Adds warning message to keepers that unclaimed amount for the current period will be forfeited.
=> Subscriptions

src/components/BuyHNY.js, src/components/Dashboard/Welcome.js, src/components/TitleHeader.js
=> Update honeyswap app url

src/hooks/useCourtContracts.js
=> Set gasLimit for claimFees function

src/components/Disputes/DisputeInfoContent.js, src/disputables/index.js, src/disputables/known-arbitrables.js, src/disputables/mappings.js, src/disputables/queries.js, src/disputables/scriptExtractors.js
closes #96 
- Fixes disputed proposals, not having associated metadata.
- Fixes disputable vote link
=> Disputed action label fixes

src/components/Dashboard/AccountBanner.js, src/components/Dashboard/AppealColateralModule.js, src/components/Dashboard/Balance.js, src/components/Dashboard/CourtStats.js, src/components/Dashboard/HNYLockedDistribution.js, src/components/Dashboard/panels/ActivateHNY.js, src/components/Dashboard/panels/DeactivateHNY.js, src/components/Dashboard/panels/HNYForm.js, src/components/Dashboard/panels/WithdrawHNY.js, src/hooks/useTokenAmountToUsd.js, src/lib/math-utils.js
=> Rounding error

src/components/Dashboard/RewardsModule.js
=> Rewards layout changes

src/hooks/useCourtContracts.js
Skips `approveAndCall` function and directly calls `jurorRegistry.stake` if allowance is sufficient. 
When calling `approveAndCall` when `allowance > 0`, errors due to the front running fix done to ERC20s approve function.
=> Stake activate: Call stake if sufficient allowance

src/components/Disputes/DisputeCurrentRuling.js, src/components/Disputes/DisputeInfo.js
- Shows dispute current ruling on reveal phase.
- Added an indicator of remaining reveals
=> Live reveals

src/disputables/index.js, src/disputables/known-arbitrables.js, src/disputables/mappings.js, src/flagged-disputes/voided-disputes.js, src/lib/web3-utils.js, src/networks.js, src/web3-contracts.js
- Creates default provider with multiple apis as done on gardens.
- Updates subgraph mapping to use gardens subgraph instead of honeypot so it can describe disputes coming from other gardens
=> Generic dispute description

src/components/Dashboard/Dashboard.js
Hiding staking rewards temporarily until we update the UI to reflect new contract changes
=> Hide staking rewards

src/hooks/useCourtContracts.js, src/hooks/useJurorSubscriptionFees.js, src/queries/court.js, src/utils/subscription-utils.js
Adds the condition of subscriptions module having enough HNY balance for rewards eligibility.
=> Subscriptions: Handle new behaviour

src/environment.js, src/hooks/subscription-hooks.js, src/hooks/useDisputes.js, src/lib/__tests__/web3-utils.test.js, src/networks.js, src/queries/disputes.js, src/utils/dispute-utils.js, yarn.lock
WIP
- Updating the RPC Gnosis in Celeste
- Some mock to fix the metadata json to dispute raised from Quests
-
=> Fix: gnosis rpc url and some mocks to dispute 4

src/components/Accordion/Accordion.js, yarn.lock
This div is blocking user interaction so put it before fixing it so the next div is drawn over it
=> Fix opened  surface block comment  interaction

.github/workflows/ci.yml, src/disputables/mappings.js, yarn.lock
=> Change to used by garden subgrapph

src/disputables/mappings.js, src/environment.js, src/hooks/useUniswapHnyPrice.js, src/networks.js, yarn.lock
Link to new subgraphs:
- Celeste: https://thegraph.com/explorer/subgraphs/HQcpdYKeSRuvjEwz8QL4nGYrJ6pUUxNoTcxssMn1Gc83?view=Overview&chain=mainnet
- Honeyswap: https://thegraph.com/explorer/subgraphs/GKLYucDsN3zVkTyki1Qmfc192i4HyUF7uqU9Py4BbmQH?view=Overview&chain=mainnet
- Gardens: https://thegraph.com/explorer/subgraphs/EucdbfTKw6d9DFeA2yHP8W9ZPciQGpAQHZMFCy3i7TxZ?view=Overview&chain=mainnet
=> Use new decentralized subgraphs
